/**
 * Full Hunared company services catalog (signup, company profile, filters).
 * Keep alphabetically sorted for searchable multi-select UX.
 */
export const COMPANY_SERVICES = [
  "Accounting",
  "Actuarial Services",
  "Administration",
  "Advertising",
  "Advertising Technology",
  "Aerospace Services",
  "Agricultural Services",
  "Air Freight",
  "Airport Services",
  "App Development",
  "Appraisal Services",
  "Architectural Services",
  "Artificial Intelligence",
  "Asset Management",
  "Audit & Assurance",
  "Automation & Control",
  "Automotive Services",
  "Aviation Services",
  "Banking Services",
  "Banking Technology",
  "Beauty & Personal Care",
  "Benefits Administration",
  "Bioinformatics",
  "Biomedical Services",
  "Blockchain Services",
  "Branding",
  "Brokerage",
  "Building Inspection",
  "Building Maintenance",
  "Building Security",
  "Business Advisory",
  "Business Development",
  "Business Intelligence",
  "Business Process Outsourcing",
  "Business Support",
  "Budgeting & Financial Planning",
  "Calibration",
  "Call Center Services",
  "Capital Management",
  "Cargo & Freight",
  "Catering",
  "Certification",
  "Chemical Services",
  "Civil Engineering",
  "Cleaning Services",
  "Cloud Services",
  "Commercial Cleaning",
  "Commissioning Services",
  "Compliance Services",
  "Construction Services",
  "Consulting Services",
  "Contract Management",
  "Corporate Finance",
  "Corporate Services",
  "Courier & Delivery",
  "Cybersecurity",
  "Data Analytics",
  "Data Center Services",
  "Data Management",
  "Disaster Recovery",
  "Digital Marketing",
  "Digital Solutions",
  "Digital Transformation",
  "Document Management",
  "Drone Services",
  "Driving Services",
  "Due Diligence",
  "E-Commerce Services",
  "Electrical Engineering",
  "Electrical Installation",
  "Electrical Testing",
  "Electronics Services",
  "Emergency Response",
  "Employee Benefits",
  "Energy Auditing",
  "Energy Consulting",
  "Energy Management",
  "Engineering Services",
  "Environmental Consulting",
  "Environmental Management",
  "Equipment Inspection",
  "Equipment Rental",
  "Event Management",
  "Exhibition Services",
  "Executive Search",
  "Export Services",
  "Facility Cleaning",
  "Facility Management",
  "Fashion Services",
  "Financial Advisory",
  "Financial Management",
  "Financial Technology (FinTech)",
  "Fire Alarm Services",
  "Fire Protection",
  "Fire Safety",
  "Firefighting Services",
  "Fleet Management",
  "Food Catering",
  "Food Processing",
  "Food Safety",
  "Forensic Services",
  "Freight Forwarding",
  "Fund Management",
  "Furniture Services",
  "General Contracting",
  "Geospatial Services",
  "Geotechnical Engineering",
  "Government Contracting",
  "Government Relations",
  "Graphic Design",
  "Ground Transportation",
  "Guest Services",
  "Hazardous Materials Services",
  "Health & Safety",
  "Healthcare Services",
  "Heavy Equipment Services",
  "Hospitality Services",
  "Hotel Management",
  "Human Resources",
  "HVAC Services",
  "Import Services",
  "Industrial Automation",
  "Industrial Cleaning",
  "Industrial Design",
  "Industrial Engineering",
  "Industrial Inspection",
  "Industrial Maintenance",
  "Industrial Repair",
  "Industrial Services",
  "Information Security",
  "Infrastructure Services",
  "Installation Services",
  "Insurance Services",
  "Intellectual Property Services",
  "Interior Design",
  "International Trade",
  "Inventory Management",
  "Investment Advisory",
  "Investment Management",
  "IT Consulting",
  "IT Services",
  "IT Support",
  "Janitorial Services",
  "Job Placement",
  "Joint Venture Service",
  "Knowledge Management",
  "Kitchen Services",
  "Laboratory Services",
  "Laboratory Testing",
  "Landscaping",
  "Legal Services",
  "Leasing Services",
  "Logistics Services",
  "Loss Prevention",
  "Machine Learning",
  "Machinery Maintenance",
  "Manpower Services",
  "Manpower Supply",
  "Management Consulting",
  "Marine Services",
  "Market Research",
  "Marketing",
  "Materials Testing",
  "Mechanical Engineering",
  "Mechanical Maintenance",
  "Media Services",
  "Medical Equipment Services",
  "Medical Services",
  "Metal Fabrication",
  "Metering Services",
  "Mining Services",
  "Mobile App Development",
  "Moving & Relocation",
  "Multimedia Production",
  "Network Cabling",
  "Network Installation",
  "Network Management",
  "Network Security",
  "Non-Destructive Testing (NDT)",
  "Notary Services",
  "Occupational Health",
  "Occupational Safety",
  "Oil & Gas Services",
  "Operations Management",
  "Outsourcing Services",
  "Painting & Coating",
  "Payroll Services",
  "Pest Control",
  "Pest Management",
  "Petroleum Services",
  "Pharmaceutical Services",
  "Photography",
  "Plumbing",
  "Port Services",
  "Procurement Services",
  "Process Engineering",
  "Product Design",
  "Product Development",
  "Professional Training",
  "Project Management",
  "Property Management",
  "Public Relations",
  "Publishing Services",
  "Quality Assurance",
  "Quality Control",
  "Quantity Surveying",
  "Real Estate Services",
  "Recruitment",
  "Recruitment Process Outsourcing",
  "Recycling",
  "Regulatory Affairs",
  "Renewable Energy",
  "Repair & Maintenance",
  "Research Services",
  "Residential Services",
  "Risk Management",
  "Road Services",
  "Robotics Services",
  "SAP & ERP Services",
  "Safety Consulting",
  "Scaffolding Services",
  "Search Engine Optimization",
  "Security Services",
  "Shipping Services",
  "Site Management",
  "Social Media Services",
  "Software Consulting",
  "Software Development",
  "Software Testing",
  "Solar Energy",
  "Solar Installation",
  "Staffing Services",
  "Storage & Warehousing",
  "Strategic Consulting",
  "Structural Engineering",
  "Supply Chain Management",
  "Surveying & Mapping",
  "Sustainability Consulting",
  "Sustainability Services",
  "System Integration",
  "Tax Advisory",
  "Technical Consulting",
  "Technical Inspection",
  "Technical Staffing",
  "Telecom Infrastructure",
  "Telecommunications",
  "Testing Services",
  "Third-Party Inspection",
  "Training & Certification",
  "Training & Development",
  "Translation & Interpretation",
  "Transport Management",
  "Transportation",
  "Travel Management",
  "Travel Services",
  "Turnaround & Shutdown",
  "Utility Management",
  "Underwriting",
  "Urban Planning",
  "UX/UI Design",
  "Valuation & Appraisal",
  "Vehicle Rental",
  "Vehicle Repair",
  "Verification & Validation",
  "Video Production",
  "Virtual Assistant",
  "Visa & Immigration",
  "Vocational Training",
  "Warehouse Management",
  "Waste Collection",
  "Waste Management",
  "Wastewater Treatment",
  "Water Treatment",
  "Web Design",
  "Web Development",
  "Web Hosting",
  "Welding",
  "Well Testing",
  "Workplace Safety",
  "Workforce Management",
  "X-Ray & Imaging",
  "Yacht Charter",
  "Yacht Management",
  "Zero-Emission Services",
  "Zoning & Land Planning",
] as const;

export type CompanyService = (typeof COMPANY_SERVICES)[number];
