// Hunared — Company categories, types, sizes, services, badges

export const COMPANY_TYPES = [
  "Private Company",
  "Public / Listed Company",
  "Government Organization",
  "Semi-Government Organization",
  "Multinational Company",
  "Non-Profit Organization",
  "NGO",
  "Charity Organization",
  "Foundation",
  "Cooperative",
  "Partnership",
  "Sole Proprietorship",
  "Family-Owned Business",
  "Startup",
  "Franchise",
  "Joint Venture",
  "Holding Company",
  "Subsidiary",
] as const;

export const BUSINESS_SIZES = [
  "Micro Enterprise",
  "Small Enterprise",
  "Medium Enterprise",
  "Small & Medium Enterprise (SME)",
  "Large Enterprise",
  "Corporate / Enterprise",
] as const;

export const INDUSTRIES = [
  "Accounting & Auditing",
  "Advertising & Marketing",
  "Aerospace & Space Technology",
  "Agriculture & Agribusiness",
  "Architecture & Design",
  "Artificial Intelligence & Data",
  "Automotive & Mobility",
  "Aviation & Airports",
  "Animal Health & Veterinary Services",
  "Banking & Financial Services",
  "Beauty & Personal Care",
  "Biotechnology & Life Sciences",
  "Blockchain & Web3",
  "Building Materials",
  "Business & Management Consulting",
  "Chemicals & Petrochemicals",
  "Cleaning & Facility Services",
  "Construction & Infrastructure",
  "Consumer Goods & Products",
  "Cybersecurity",
  "Defense & Security",
  "Digital Services & Platforms",
  "Distribution & Wholesale",
  "E-Commerce & Online Marketplaces",
  "Education & Training",
  "Electronics & Electrical",
  "Energy & Power",
  "Engineering & Technical Services",
  "Entertainment & Media",
  "Environmental Services",
  "Events & Exhibitions",
  "Facilities Management",
  "Fashion & Apparel",
  "Film, Television & Production",
  "Food & Beverage",
  "Forestry & Timber",
  "Freight & Cargo Services",
  "Furniture & Home",
  "Government & Public Sector",
  "Gaming & Interactive Entertainment",
  "Healthcare & Medical Services",
  "Hospitality & Tourism",
  "Human Resources & Recruitment",
  "Import & Export",
  "Industrial Equipment & Machinery",
  "Industrial Manufacturing",
  "Industrial Services",
  "Information Technology & Software",
  "Inspection, Testing & Certification",
  "Internet & Digital Technology",
  "Jewelry & Precious Metals",
  "Knowledge & Professional Education",
  "Legal & Compliance Services",
  "Logistics & Supply Chain",
  "Luxury Goods & Lifestyle",
  "Manufacturing",
  "Manpower Services",
  "Marine & Maritime",
  "Marketing & Communications",
  "Media & Publishing",
  "Metals, Steel & Metal Products",
  "Mining & Minerals",
  "Non-Profit & Social Services",
  "Oil & Gas",
  "Online Services",
  "Packaging & Printing",
  "Pharmaceuticals",
  "Plastics & Rubber Products",
  "Professional & Business Services",
  "Procurement & Sourcing",
  "Property Management",
  "Public Utilities",
  "Quality Assurance & Quality Control",
  "Real Estate & Property",
  "Renewable Energy",
  "Research & Development",
  "Retail & Consumer Commerce",
  "Repair & Technical Services",
  "Rental & Leasing",
  "Safety, Health & Environment (HSE)",
  "Science & Technology",
  "Security Services",
  "Shipping & Ports",
  "Social & Community Services",
  "Software & IT Services",
  "Sports & Fitness",
  "Telecommunications",
  "Textile & Leather",
  "Transportation & Mobility",
  "Travel & Tourism",
  "Technology & Innovation",
  "Trading & Distribution",
  "Utilities & Public Services",
  "Waste Management & Recycling",
  "Water & Wastewater",
  "Wholesale & Distribution",
  "Zoological & Animal Services",
] as const;

export const BUSINESS_ACTIVITIES = [
  "Manufacturer",
  "Supplier",
  "Vendor",
  "Distributor",
  "Wholesaler",
  "Retailer",
  "Trader",
  "Importer",
  "Exporter",
  "Import & Export",
  "Contractor",
  "Subcontractor",
  "Service Provider",
  "Consultant",
  "Recruiter",
  "Manpower Provider",
  "Equipment Rental",
  "Product Seller",
  "Technology Provider",
  "Training Provider",
  "Certification Provider",
  "Maintenance Provider",
  "Installer",
  "Repair Provider",
  "Project Developer",
  "Property Developer",
  "Franchise Operator",
  "E-Commerce",
  "Marketplace",
  "Other",
] as const;

// High-level service groups (can be expanded later)
export const SERVICE_GROUPS: Record<string, string[]> = {
  "Oil & Gas Services": [
    "Drilling",
    "Oilfield Services",
    "Well Services",
    "Pipeline Services",
    "Refinery Services",
    "Petrochemical Services",
    "Gas Processing",
    "LNG Services",
    "Tank Farm Services",
    "Shutdown & Turnaround",
    "Plant Operations",
  ],
  "Construction Services": [
    "General Construction",
    "Civil Construction",
    "Building Construction",
    "Industrial Construction",
    "Infrastructure",
    "Road Construction",
    "Structural Works",
    "Concrete Works",
    "Excavation",
    "Piling & Foundations",
    "Demolition",
    "Renovation",
    "Waterproofing",
    "Roofing",
    "Flooring",
    "Interior Fit-Out",
    "Landscaping",
  ],
  "Engineering Services": [
    "Civil Engineering",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Instrumentation Engineering",
    "Chemical Engineering",
    "Structural Engineering",
    "Industrial Engineering",
    "Process Engineering",
    "Project Engineering",
    "Engineering Design",
    "CAD / Drafting",
    "BIM",
    "3D Modeling",
    "Engineering Consultancy",
  ],
  "Mechanical Services": [
    "Mechanical Installation",
    "Mechanical Maintenance",
    "Rotating Equipment",
    "Pumps",
    "Compressors",
    "Turbines",
    "Valves",
    "Piping",
    "Welding",
    "Fabrication",
    "Machining",
    "Alignment",
    "Balancing",
    "Hydrotesting",
    "Equipment Overhaul",
  ],
  "Electrical Services": [
    "Electrical Installation",
    "Electrical Maintenance",
    "Electrical Testing",
    "Power Distribution",
    "Cable Installation",
    "Generator Services",
    "Transformer Services",
    "Switchgear",
    "Substation Services",
    "Lighting",
    "UPS Systems",
    "Earthing & Lightning Protection",
  ],
  "Instrumentation & Automation": [
    "Instrument Installation",
    "Instrument Maintenance",
    "Instrument Calibration",
    "PLC",
    "DCS",
    "SCADA",
    "HMI",
    "Industrial Automation",
    "Process Control",
    "Control Valves",
    "Fire & Gas Systems",
    "Analyzer Systems",
    "Testing & Commissioning",
  ],
  "Maintenance Services": [
    "Industrial Maintenance",
    "Plant Maintenance",
    "Preventive Maintenance",
    "Corrective Maintenance",
    "Predictive Maintenance",
    "Facility Maintenance",
    "Building Maintenance",
    "HVAC Maintenance",
    "Plumbing",
    "Cleaning",
    "Pest Control",
    "Landscaping",
  ],
  "IT & Technology Services": [
    "IT Support",
    "IT Consulting",
    "Software Development",
    "Web Development",
    "Mobile App Development",
    "Cloud Services",
    "Cybersecurity",
    "Network Services",
    "Data Analytics",
    "AI & Machine Learning",
    "ERP Solutions",
    "CRM Solutions",
    "DevOps",
    "Digital Transformation",
  ],
  "Recruitment & HR Services": [
    "Recruitment",
    "Technical Recruitment",
    "Executive Recruitment",
    "Manpower Supply",
    "Temporary Staffing",
    "Permanent Staffing",
    "Contract Staffing",
    "Workforce Outsourcing",
    "HR Consultancy",
    "Payroll Services",
    "Visa & Immigration Services",
  ],
  "Safety, Inspection & Certification": [
    "HSE Services",
    "Safety Consultancy",
    "Risk Assessment",
    "Safety Auditing",
    "Fire Safety",
    "Fire Protection",
    "QA/QC",
    "NDT",
    "Welding Inspection",
    "Third-Party Inspection",
    "Equipment Inspection",
    "Calibration",
    "Certification",
    "Compliance Auditing",
  ],
  "Logistics & Transportation": [
    "Logistics",
    "Freight Forwarding",
    "Warehousing",
    "Distribution",
    "Road Transportation",
    "Heavy Transport",
    "Cargo Transportation",
    "Courier Services",
    "Customs Clearance",
    "Import & Export",
    "Fleet Management",
    "Shipping",
    "Cold Chain",
  ],
  "Healthcare Services": [
    "Hospitals",
    "Clinics",
    "Medical Centers",
    "Laboratories",
    "Diagnostics",
    "Pharmacy",
    "Dental Services",
    "Home Healthcare",
    "Nursing",
    "Physiotherapy",
    "Medical Equipment",
    "Telemedicine",
  ],
  "Education & Training": [
    "Schools",
    "Universities",
    "Vocational Training",
    "Technical Training",
    "Professional Training",
    "Corporate Training",
    "Safety Training",
    "Online Training",
    "Language Training",
    "Skills Development",
    "Certification Training",
    "Examination Services",
  ],
  "Finance & Professional Services": [
    "Banking",
    "Accounting",
    "Auditing",
    "Tax Services",
    "Insurance",
    "Investment",
    "Financial Consultancy",
    "Legal Services",
    "Business Consultancy",
    "Management Consultancy",
    "HR Consultancy",
    "Market Research",
  ],
  "Real Estate": [
    "Property Development",
    "Property Sales",
    "Property Leasing",
    "Property Management",
    "Facility Management",
    "Property Valuation",
    "Real Estate Consultancy",
    "Real Estate Investment",
  ],
  "Hospitality & Tourism": [
    "Hotels",
    "Resorts",
    "Restaurants",
    "Catering",
    "Food Delivery",
    "Travel Agency",
    "Tour Operations",
    "Event Management",
    "Conference Services",
  ],
  "Security": [
    "Security Guard Services",
    "Industrial Security",
    "Corporate Security",
    "Event Security",
    "CCTV",
    "Access Control",
    "Alarm Systems",
    "Security Monitoring",
    "Security Consultancy",
    "Security Training",
  ],
  "Energy & Environment": [
    "Power Generation",
    "Power Distribution",
    "Solar Energy",
    "Renewable Energy",
    "Energy Management",
    "Water Treatment",
    "Wastewater Treatment",
    "Desalination",
    "Waste Management",
    "Recycling",
    "Environmental Consultancy",
    "Environmental Testing",
  ],
};

export const COMPANY_BADGES = [
  { key: "verified_company", label: "Verified Company", icon: "✓" },
  { key: "verified_employer", label: "Verified Employer", icon: "✓" },
  { key: "featured", label: "Featured Company", icon: "⭐" },
  { key: "hiring_now", label: "Hiring Now", icon: "🔥" },
  { key: "top_rated", label: "Top Rated", icon: "🏆" },
  { key: "highly_followed", label: "Highly Followed", icon: "🌟" },
  { key: "new_company", label: "New Company", icon: "🆕" },
  { key: "fast_growing", label: "Fast Growing", icon: "🚀" },
  { key: "top_employer", label: "Top Employer", icon: "💼" },
  { key: "global_employer", label: "Global Employer", icon: "🌍" },
  { key: "multiple_locations", label: "Multiple Locations", icon: "🏢" },
  { key: "remote_friendly", label: "Remote-Friendly", icon: "🏠" },
  { key: "graduate_friendly", label: "Graduate-Friendly", icon: "🎓" },
  { key: "internship_provider", label: "Internship Provider", icon: "👨‍🎓" },
  { key: "equal_opportunity", label: "Equal Opportunity Employer", icon: "🤝" },
  { key: "inclusive", label: "Inclusive Employer", icon: "♿" },
  { key: "sustainability", label: "Sustainability Focused", icon: "🌱" },
  { key: "safety_certified", label: "Safety Certified", icon: "🛡️" },
  { key: "iso_certified", label: "ISO Certified", icon: "📜" },
  { key: "contractor", label: "Contractor", icon: "🏗️" },
  { key: "manpower_provider", label: "Manpower Provider", icon: "👷" },
  { key: "training_provider", label: "Training Provider", icon: "🎓" },
] as const;

export type CompanyType = (typeof COMPANY_TYPES)[number];
export type BusinessSize = (typeof BUSINESS_SIZES)[number];
export type Industry = (typeof INDUSTRIES)[number];
export type BusinessActivity = (typeof BUSINESS_ACTIVITIES)[number];
