import {
  Briefcase,
  GraduationCap,
  Wrench,
  Home,
  ShoppingBag,
  Megaphone,
  Car,
  Laptop,
  Building2,
  Search,
  Gift,
  CalendarDays,
  Users,
  Tag,
  Sofa,
} from "lucide-react";

/** Category chips for homepage Create Ad section and related UI */
export const CREATE_AD_CATEGORIES = [
  { id: "jobs", label: "Jobs", icon: Briefcase, href: "/dashboard/jobs/new" },
  { id: "for-sale", label: "For Sale", icon: Tag, href: "/dashboard/market/new?category=for_sale" },
  { id: "services", label: "Services", icon: Wrench, href: "/dashboard/market/new?category=services" },
  { id: "property", label: "Property", icon: Building2, href: "/dashboard/market/new?category=property" },
  { id: "accommodation", label: "Accommodation", icon: Sofa, href: "/dashboard/market/new?category=accommodation" },
  { id: "vehicles", label: "Vehicles", icon: Car, href: "/dashboard/market/new?category=vehicles" },
  { id: "electronics", label: "Electronics", icon: Laptop, href: "/dashboard/market/new?category=electronics" },
  { id: "learning", label: "Learning", icon: GraduationCap, href: "/dashboard/articles/new" },
  { id: "marketplace", label: "Marketplace", icon: ShoppingBag, href: "/dashboard/market/new" },
  { id: "wanted", label: "Wanted", icon: Search, href: "/dashboard/market/new?category=wanted" },
  { id: "community", label: "Community", icon: Users, href: "/dashboard/market/new?category=community" },
  { id: "events", label: "Events", icon: CalendarDays, href: "/dashboard/market/new?category=events" },
  { id: "articles", label: "Articles", icon: Megaphone, href: "/dashboard/articles/new" },
  { id: "free", label: "Free Items", icon: Gift, href: "/dashboard/market/new?category=free_items" },
  { id: "for-rent", label: "For Rent", icon: Home, href: "/dashboard/market/new?category=for_rent" },
];
