export type CurrencyInfo = {
  code: string; // ISO 4217
  name: string;
  symbol: string;
  decimals?: number;
};

/** Global ISO 4217 currencies */
export const CURRENCIES: CurrencyInfo[] = [
  { code: "AED", name: "United Arab Emirates Dirham", symbol: "د.إ", decimals: 2 },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", decimals: 2 },
  { code: "ALL", name: "Albanian Lek", symbol: "L", decimals: 2 },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", decimals: 2 },
  { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ", decimals: 2 },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", decimals: 2 },
  { code: "ARS", name: "Argentine Peso", symbol: "$", decimals: 2 },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", decimals: 2 },
  { code: "AWG", name: "Aruban Florin", symbol: "ƒ", decimals: 2 },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", decimals: 2 },
  { code: "BAM", name: "Bosnia and Herzegovina Convertible Mark", symbol: "KM", decimals: 2 },
  { code: "BBD", name: "Barbados Dollar", symbol: "$", decimals: 2 },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", decimals: 2 },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", decimals: 2 },
  { code: "BHD", name: "Bahraini Dinar", symbol: "د.ب", decimals: 3 },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu", decimals: 0 },
  { code: "BMD", name: "Bermudian Dollar", symbol: "$", decimals: 2 },
  { code: "BND", name: "Brunei Dollar", symbol: "$", decimals: 2 },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", decimals: 2 },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", decimals: 2 },
  { code: "BSD", name: "Bahamian Dollar", symbol: "$", decimals: 2 },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", decimals: 2 },
  { code: "BWP", name: "Botswana Pula", symbol: "P", decimals: 2 },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", decimals: 2 },
  { code: "BZD", name: "Belize Dollar", symbol: "$", decimals: 2 },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", decimals: 2 },
  { code: "CDF", name: "Congolese Franc", symbol: "FC", decimals: 2 },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF", decimals: 2 },
  { code: "CLP", name: "Chilean Peso", symbol: "$", decimals: 0 },
  { code: "CNY", name: "Chinese Yuan Renminbi", symbol: "¥", decimals: 2 },
  { code: "COP", name: "Colombian Peso", symbol: "$", decimals: 2 },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡", decimals: 2 },
  { code: "CUP", name: "Cuban Peso", symbol: "$", decimals: 2 },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$", decimals: 2 },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", decimals: 2 },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", decimals: 0 },
  { code: "DKK", name: "Danish Krone", symbol: "kr", decimals: 2 },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", decimals: 2 },
  { code: "DZD", name: "Algerian Dinar", symbol: "دج", decimals: 2 },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£", decimals: 2 },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", decimals: 2 },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", decimals: 2 },
  { code: "EUR", name: "Euro", symbol: "€", decimals: 2 },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", decimals: 2 },
  { code: "FKP", name: "Falkland Islands Pound", symbol: "£", decimals: 2 },
  { code: "GBP", name: "British Pound Sterling", symbol: "£", decimals: 2 },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", decimals: 2 },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", decimals: 2 },
  { code: "GIP", name: "Gibraltar Pound", symbol: "£", decimals: 2 },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", decimals: 2 },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", decimals: 0 },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", decimals: 2 },
  { code: "GYD", name: "Guyanese Dollar", symbol: "$", decimals: 2 },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", decimals: 2 },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", decimals: 2 },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", decimals: 2 },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", decimals: 2 },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", decimals: 2 },
  { code: "ILS", name: "Israeli New Shekel", symbol: "₪", decimals: 2 },
  { code: "INR", name: "Indian Rupee", symbol: "₹", decimals: 2 },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", decimals: 3 },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", decimals: 2 },
  { code: "ISK", name: "Icelandic Króna", symbol: "kr", decimals: 0 },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$", decimals: 2 },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", decimals: 3 },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", decimals: 0 },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", decimals: 2 },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "с", decimals: 2 },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", decimals: 2 },
  { code: "KMF", name: "Comorian Franc", symbol: "CF", decimals: 0 },
  { code: "KPW", name: "North Korean Won", symbol: "₩", decimals: 2 },
  { code: "KRW", name: "South Korean Won", symbol: "₩", decimals: 0 },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", decimals: 3 },
  { code: "KYD", name: "Cayman Islands Dollar", symbol: "CI$", decimals: 2 },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", decimals: 2 },
  { code: "LAK", name: "Lao Kip", symbol: "₭", decimals: 2 },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", decimals: 2 },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", decimals: 2 },
  { code: "LRD", name: "Liberian Dollar", symbol: "$", decimals: 2 },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", decimals: 2 },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", decimals: 3 },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", decimals: 2 },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", decimals: 2 },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", decimals: 2 },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", decimals: 2 },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K", decimals: 2 },
  { code: "MNT", name: "Mongolian Tögrög", symbol: "₮", decimals: 2 },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP$", decimals: 2 },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", decimals: 2 },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨", decimals: 2 },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", decimals: 2 },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", decimals: 2 },
  { code: "MXN", name: "Mexican Peso", symbol: "MX$", decimals: 2 },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", decimals: 2 },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT", decimals: 2 },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$", decimals: 2 },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", decimals: 2 },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", decimals: 2 },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", decimals: 2 },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", decimals: 2 },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", decimals: 2 },
  { code: "OMR", name: "Omani Rial", symbol: "ر.ع.", decimals: 3 },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", decimals: 2 },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/", decimals: 2 },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", decimals: 2 },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", decimals: 2 },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", decimals: 2 },
  { code: "PLN", name: "Polish Złoty", symbol: "zł", decimals: 2 },
  { code: "PYG", name: "Paraguayan Guaraní", symbol: "₲", decimals: 0 },
  { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق", decimals: 2 },
  { code: "RON", name: "Romanian Leu", symbol: "lei", decimals: 2 },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин", decimals: 2 },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", decimals: 2 },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw", decimals: 0 },
  { code: "SAR", name: "Saudi Riyal", symbol: "ر.س", decimals: 2 },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$", decimals: 2 },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨", decimals: 2 },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س.", decimals: 2 },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", decimals: 2 },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", decimals: 2 },
  { code: "SHP", name: "Saint Helena Pound", symbol: "£", decimals: 2 },
  { code: "SLE", name: "Sierra Leonean Leone", symbol: "Le", decimals: 2 },
  { code: "SOS", name: "Somali Shilling", symbol: "S", decimals: 2 },
  { code: "SRD", name: "Surinamese Dollar", symbol: "$", decimals: 2 },
  { code: "SSP", name: "South Sudanese Pound", symbol: "£", decimals: 2 },
  { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db", decimals: 2 },
  { code: "SYP", name: "Syrian Pound", symbol: "£", decimals: 2 },
  { code: "SZL", name: "Eswatini Lilangeni", symbol: "E", decimals: 2 },
  { code: "THB", name: "Thai Baht", symbol: "฿", decimals: 2 },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "ЅМ", decimals: 2 },
  { code: "TMT", name: "Turkmenistan Manat", symbol: "m", decimals: 2 },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", decimals: 3 },
  { code: "TOP", name: "Tongan Paʻanga", symbol: "T$", decimals: 2 },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", decimals: 2 },
  { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$", decimals: 2 },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", decimals: 2 },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", decimals: 2 },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", decimals: 2 },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh", decimals: 0 },
  { code: "USD", name: "United States Dollar", symbol: "$", decimals: 2 },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", decimals: 2 },
  { code: "UZS", name: "Uzbekistani Som", symbol: "soʻm", decimals: 2 },
  { code: "VES", name: "Venezuelan Bolívar", symbol: "Bs.", decimals: 2 },
  { code: "VND", name: "Vietnamese Đồng", symbol: "₫", decimals: 0 },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", decimals: 0 },
  { code: "WST", name: "Samoan Tālā", symbol: "WS$", decimals: 2 },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA", decimals: 0 },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$", decimals: 2 },
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA", decimals: 0 },
  { code: "XPF", name: "CFP Franc", symbol: "₣", decimals: 0 },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", decimals: 2 },
  { code: "ZAR", name: "South African Rand", symbol: "R", decimals: 2 },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", decimals: 2 },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$", decimals: 2 },
];

export function getCurrency(code: string | null | undefined): CurrencyInfo {
  const found = CURRENCIES.find((c) => c.code === (code ?? "").toUpperCase());
  return found ?? CURRENCIES.find((c) => c.code === "USD")!;
}

/** Country ISO 3166-1 alpha-2 → default currency */
export function currencyForCountry(
  countryCode: string | null | undefined
): string {
  const map: Record<string, string> = {
    AF: "AFN",
    AL: "ALL",
    DZ: "DZD",
    AD: "EUR",
    AO: "AOA",
    AG: "XCD",
    AR: "ARS",
    AM: "AMD",
    AU: "AUD",
    AT: "EUR",
    AZ: "AZN",
    BS: "BSD",
    BH: "BHD",
    BD: "BDT",
    BB: "BBD",
    BY: "BYN",
    BE: "EUR",
    BZ: "BZD",
    BJ: "XOF",
    BT: "BTN",
    BO: "BOB",
    BA: "BAM",
    BW: "BWP",
    BR: "BRL",
    BN: "BND",
    BG: "BGN",
    BF: "XOF",
    BI: "BIF",
    CV: "CVE",
    KH: "KHR",
    CM: "XAF",
    CA: "CAD",
    CF: "XAF",
    TD: "XAF",
    CL: "CLP",
    CN: "CNY",
    CO: "COP",
    KM: "KMF",
    CG: "XAF",
    CD: "CDF",
    CR: "CRC",
    CI: "XOF",
    HR: "EUR",
    CU: "CUP",
    CY: "EUR",
    CZ: "CZK",
    DK: "DKK",
    DJ: "DJF",
    DM: "XCD",
    DO: "DOP",
    EC: "USD",
    EG: "EGP",
    SV: "USD",
    GQ: "XAF",
    ER: "ERN",
    EE: "EUR",
    SZ: "SZL",
    ET: "ETB",
    FJ: "FJD",
    FI: "EUR",
    FR: "EUR",
    GA: "XAF",
    GM: "GMD",
    GE: "GEL",
    DE: "EUR",
    GH: "GHS",
    GR: "EUR",
    GD: "XCD",
    GT: "GTQ",
    GN: "GNF",
    GW: "XOF",
    GY: "GYD",
    HT: "HTG",
    HN: "HNL",
    HU: "HUF",
    IS: "ISK",
    IN: "INR",
    ID: "IDR",
    IR: "IRR",
    IQ: "IQD",
    IE: "EUR",
    IL: "ILS",
    IT: "EUR",
    JM: "JMD",
    JP: "JPY",
    JO: "JOD",
    KZ: "KZT",
    KE: "KES",
    KI: "AUD",
    KP: "KPW",
    KR: "KRW",
    KW: "KWD",
    KG: "KGS",
    LA: "LAK",
    LV: "EUR",
    LB: "LBP",
    LS: "LSL",
    LR: "LRD",
    LY: "LYD",
    LI: "CHF",
    LT: "EUR",
    LU: "EUR",
    MG: "MGA",
    MW: "MWK",
    MY: "MYR",
    MV: "MVR",
    ML: "XOF",
    MT: "EUR",
    MH: "USD",
    MR: "MRU",
    MU: "MUR",
    MX: "MXN",
    FM: "USD",
    MD: "MDL",
    MC: "EUR",
    MN: "MNT",
    ME: "EUR",
    MA: "MAD",
    MZ: "MZN",
    MM: "MMK",
    NA: "NAD",
    NR: "AUD",
    NP: "NPR",
    NL: "EUR",
    NZ: "NZD",
    NI: "NIO",
    NE: "XOF",
    NG: "NGN",
    MK: "MKD",
    NO: "NOK",
    OM: "OMR",
    PK: "PKR",
    PW: "USD",
    PA: "PAB",
    PG: "PGK",
    PY: "PYG",
    PE: "PEN",
    PH: "PHP",
    PL: "PLN",
    PT: "EUR",
    QA: "QAR",
    RO: "RON",
    RU: "RUB",
    RW: "RWF",
    KN: "XCD",
    LC: "XCD",
    VC: "XCD",
    WS: "WST",
    SM: "EUR",
    ST: "STN",
    SA: "SAR",
    SN: "XOF",
    RS: "RSD",
    SC: "SCR",
    SL: "SLE",
    SG: "SGD",
    SK: "EUR",
    SI: "EUR",
    SB: "SBD",
    SO: "SOS",
    ZA: "ZAR",
    SS: "SSP",
    ES: "EUR",
    LK: "LKR",
    SD: "SDG",
    SR: "SRD",
    SE: "SEK",
    CH: "CHF",
    SY: "SYP",
    TJ: "TJS",
    TZ: "TZS",
    TH: "THB",
    TL: "USD",
    TG: "XOF",
    TO: "TOP",
    TT: "TTD",
    TN: "TND",
    TR: "TRY",
    TM: "TMT",
    TV: "AUD",
    UG: "UGX",
    UA: "UAH",
    AE: "AED",
    GB: "GBP",
    US: "USD",
    UY: "UYU",
    UZ: "UZS",
    VU: "VUV",
    VA: "EUR",
    VE: "VES",
    VN: "VND",
    YE: "YER",
    ZM: "ZMW",
    ZW: "ZWL",
  };
  return map[(countryCode ?? "").toUpperCase()] ?? "USD";
}

/**
 * Display money: always show amount + ISO code so $ / Rs are not ambiguous.
 * Example: "5,000 SAR" or "1,500 USD"
 */
export function formatMoney(
  price: string | number | null | undefined,
  currency?: string | null
): string {
  if (price == null || String(price).trim() === "") return "";
  const p = String(price).trim();
  // Text-only rates (e.g. Negotiable) — never prefix currency alone
  if (!/\d/.test(p)) return p;
  const cur = (currency || "").trim();
  return cur ? `${cur} ${p}` : p;
}

/** Job card / detail salary line. Prefer real rate when present; never hide amount. */
export function formatJobSalary(
  salaryRate: string | number | null | undefined,
  currency?: string | null,
  salaryType?: string | null
): string {
  const type = (salaryType || "").trim();
  const rate = salaryRate != null ? String(salaryRate).trim() : "";
  const hasNumericRate = Boolean(rate && /\d/.test(rate));

  // Explicit “discuss later”
  if (type === "After Interview" && !hasNumericRate) return "To be discussed";

  // Numeric amount always wins over a Negotiable label
  if (hasNumericRate) {
    const money = formatMoney(rate, currency);
    if (type === "Hourly") return `${money} / hr`;
    if (type === "Monthly") return `${money} / mo`;
    return money;
  }

  // Text-only rate (e.g. "Negotiable" stored in rate)
  if (rate && !hasNumericRate) return rate;

  if (type === "Negotiable") return "Negotiable";
  if (type === "After Interview") return "To be discussed";
  if (type) return type;
  return "";
}

/** Label for dropdowns */
export function currencyOptionLabel(c: CurrencyInfo): string {
  return `${c.code} ${c.symbol} — ${c.name}`;
}