/** Common IANA time zones for Hunared users (Gulf + global hubs). */
export const TIMEZONES: { value: string; label: string }[] = [
  { value: "Asia/Riyadh", label: "Saudi Arabia (Riyadh) — GMT+3" },
  { value: "Asia/Dubai", label: "UAE (Dubai) — GMT+4" },
  { value: "Asia/Qatar", label: "Qatar (Doha) — GMT+3" },
  { value: "Asia/Kuwait", label: "Kuwait — GMT+3" },
  { value: "Asia/Bahrain", label: "Bahrain — GMT+3" },
  { value: "Asia/Muscat", label: "Oman (Muscat) — GMT+4" },
  { value: "Asia/Karachi", label: "Pakistan (Karachi) — GMT+5" },
  { value: "Asia/Kolkata", label: "India (Kolkata) — GMT+5:30" },
  { value: "Asia/Dhaka", label: "Bangladesh (Dhaka) — GMT+6" },
  { value: "Asia/Manila", label: "Philippines (Manila) — GMT+8" },
  { value: "Asia/Jakarta", label: "Indonesia (Jakarta) — GMT+7" },
  { value: "Asia/Singapore", label: "Singapore — GMT+8" },
  { value: "Asia/Shanghai", label: "China (Shanghai) — GMT+8" },
  { value: "Europe/London", label: "United Kingdom (London)" },
  { value: "Europe/Berlin", label: "Central Europe (Berlin)" },
  { value: "Europe/Istanbul", label: "Turkey (Istanbul)" },
  { value: "Africa/Cairo", label: "Egypt (Cairo)" },
  { value: "Africa/Nairobi", label: "Kenya (Nairobi)" },
  { value: "America/New_York", label: "US Eastern (New York)" },
  { value: "America/Chicago", label: "US Central (Chicago)" },
  { value: "America/Los_Angeles", label: "US Pacific (Los Angeles)" },
  { value: "UTC", label: "UTC" },
];
